### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by anissen** [Clever-Coding/parcel-cli#1]
This is a neat project but a `README.md` is sorely missing. Please explain the purpose of this repository and how to use the CLI :+1:.

Also, you should update your [blog post](http://snowkit.org/2015/07/03/slush-generator-for-luxe/) with a link to this repository as well.

**Comment by escargotprodige** [comment]
Fixing this right now :+1: !

**Comment by escargotprodige** [comment]
Fixed :+1:

**Comment by anissen** [comment]
Great. I've added this repository and `slush-luxe` to [awesome-snowkit](https://github.com/anissen/awesome-snowkit/blob/master/README.md#generators) :smiley:

**Comment by escargotprodige** [comment]
Thanks :)
